    - name: Set Pull Request Environment Variables
      shell: bash
      run: |
        if [ "${{ inputs.EVENT_ACTION }}" == "no_code_of_conduct" ]; then
          echo "PULL_REQUEST_FROM_BRANCH=add-code-of-conduct" >> $GITHUB_ENV
          echo "PULL_REQUEST_TITLE=Add Code of Conduct" >> $GITHUB_ENV
          echo "PULL_REQUEST_BODY=This pull request adds a Code of Conduct to the repository." >> $GITHUB_ENV
        elif [ "${{ inputs.EVENT_ACTION }}" == "handle_contributor_covenant_1_4" ]; then
          echo "PULL_REQUEST_FROM_BRANCH=update-code-of-conduct" >> $GITHUB_ENV
          echo "PULL_REQUEST_TITLE=Update Code of Conduct to Contributor Covenant 2.1" >> $GITHUB_ENV
          echo "PULL_REQUEST_BODY=We have detected that your current Code of Conduct is based on Contributor Covenant version 1.4. It would be great to update it to the latest version 2.1 to ensure it includes the most recent improvements and guidelines." >> $GITHUB_ENV
        fi

    - name: Create Pull Request
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.USER_GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "main"
        PULL_REQUEST_FROM_BRANCH: ${{ env.PULL_REQUEST_FROM_BRANCH }}
        PULL_REQUEST_TITLE: ${{ env.PULL_REQUEST_TITLE }}
        PULL_REQUEST_BODY: ${{ env.PULL_REQUEST_BODY }}
        PULL_REQUEST_LABELS: "code of conduct, documentation"
